services:

  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - app
    profiles: ["dev"]

  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    profiles: ["dev"]
    
  app-prod:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    profiles: ["prod"]

  web-prod:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - app-prod
    profiles: ["prod"]