services:

  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - app

  app:
    build: .
    expose:
      - "3000"
    volumes:
      - ./index.html:/app/index.html