services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    profiles: ["dev"]

  nginx-prod:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - backend-prod
    profiles: ["prod"]

  backend:
    build:
      context: ./backend
    env_file: .env
    profiles: ["dev"]
    networks:
      default:
        aliases:
          - backend

  backend-prod:
    build:
      context: ./backend
    env_file: .env
    profiles: ["prod"]
    networks:
      default:
        aliases:
          - backend

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
    profiles: ["dev"]
    networks:
      default:
        aliases:
          - frontend
