server.port=8080
spring.application.name=home-dashboard

dashboard.stationboard.station=${STATION_NAME:Zurich HB}
dashboard.stationboard.limit=5
dashboard.stationboard.api-url=https://transport.opendata.ch/v1/stationboard

dashboard.lights.user=${HUE_USER:}
dashboard.lights.bridge-address-fallback=${HUE_BRIDGE_ADDRESS:}
dashboard.lights.discovery-api-url=http://discovery.meethue.com/

dashboard.calendar.zip=${ZIP:8000}

dashboard.wifi.ssid=${WIFI_SSID:}
dashboard.wifi.password=${WIFI_PASSWORD:}
